### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Sagiri-kawaii01** [WuliAPO/Fuck_QCZJ#11]
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
============= RESTART: C:\Users\11047\Desktop\Fuck_QCZJ\main.py =============
Traceback (most recent call last):
  File "C:\Users\11047\AppData\Roaming\Python\Python37\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\11047\AppData\Roaming\Python\Python37\site-packages\urllib3\connectionpool.py", line 994, in _prepare_proxy
    conn.connect()
  File "C:\Users\11047\AppData\Roaming\Python\Python37\site-packages\urllib3\connection.py", line 364, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\11047\AppData\Roaming\Python\Python37\site-packages\urllib3\connection.py", line 507, in _connect_tls_proxy
    ssl_context=ssl_context,
  File "C:\Users\11047\AppData\Roaming\Python\Python37\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\11047\AppData\Roaming\Python\Python37\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "E:\python\Python37\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "E:\python\Python37\lib\ssl.py", line 853, in _create
    self.do_handshake()
  File "E:\python\Python37\lib\ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1051)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\python\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\11047\AppData\Roaming\Python\Python37\site-packages\urllib3\connectionpool.py", line 786, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\11047\AppData\Roaming\Python\Python37\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='qczj.h5yunban.com', port=443): Max retries exceeded with url: /qczj-youth-learning/cgi-bin/login/we-chat/callback?callback=https%3A%2F%2Fqczj.h5yunban.com%2Fqczj-youth-learning%2Findex.php&scope=snsapi_userinfo&appid=wx56b888a1409a2920&openid=oO-a2t3kYWrdpurwM5OqrHDn_0H4&nickname=ZhangSan&headimg=&time=1666166977&source=common&sign=&t=1666166977 (Caused by ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1051)'))))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\11047\Desktop\Fuck_QCZJ\main.py", line 62, in <module>
    access_token = getAccessToken(session,openid)
  File "C:\Users\11047\Desktop\Fuck_QCZJ\main.py", line 12, in getAccessToken
    res = session.get(url)
  File "E:\python\Python37\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "E:\python\Python37\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\python\Python37\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "E:\python\Python37\lib\site-packages\requests\adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='qczj.h5yunban.com', port=443): Max retries exceeded with url: /qczj-youth-learning/cgi-bin/login/we-chat/callback?callback=https%3A%2F%2Fqczj.h5yunban.com%2Fqczj-youth-learning%2Findex.php&scope=snsapi_userinfo&appid=wx56b888a1409a2920&openid=oO-a2t3kYWrdpurwM5OqrHDn_0H4&nickname=ZhangSan&headimg=&time=1666166977&source=common&sign=&t=1666166977 (Caused by ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1051)'))))
>>>

**Comment by Sagiri-kawaii01** [comment]
没事了，是开了抓包工具忘了关，关掉再运行就可以了
